from fpdf import FPDF


def safe_text(text):
    return str(text).encode(
        "latin-1",
        "replace"
    ).decode("latin-1")


def create_report(
    issues,
    analysis,
    stats=None,
    insights=None,
    severity=None
):

    pdf = FPDF()

    pdf.set_author(
        "Pallavi Gollu"
    )

    pdf.set_title(
        "Wireless Diagnostics Report"
    )

    pdf.add_page()

    # ==========================
    # TITLE
    # ==========================

    pdf.set_font(
        "Arial",
        "B",
        16
    )

    pdf.cell(
        200,
        10,
        txt="Wireless Diagnostics Report",
        ln=True
    )

    pdf.ln(5)

    # ==========================
    # ISSUE SUMMARY
    # ==========================

    pdf.set_font(
        "Arial",
        "B",
        12
    )

    pdf.cell(
        200,
        10,
        txt="Issue Summary",
        ln=True
    )

    pdf.set_font(
        "Arial",
        size=11
    )

    pdf.cell(
        200,
        8,
        txt=f"Authentication Failures: {issues['Authentication Failure']}",
        ln=True
    )

    pdf.cell(
        200,
        8,
        txt=f"DHCP Timeouts: {issues['DHCP Timeout']}",
        ln=True
    )

    pdf.cell(
        200,
        8,
        txt=f"Disconnections: {issues['Disconnection']}",
        ln=True
    )

    pdf.cell(
        200,
        8,
        txt=f"Association Failures: {issues['Association Failure']}",
        ln=True
    )

    pdf.ln(5)

    # ==========================
    # SEVERITY
    # ==========================

    if severity:

        pdf.set_font(
            "Arial",
            "B",
            12
        )

        pdf.cell(
            200,
            10,
            txt=f"Network Severity: {safe_text(severity)}",
            ln=True
        )

    pdf.ln(5)

    # ==========================
    # AI DIAGNOSIS
    # ==========================

    pdf.set_font(
        "Arial",
        "B",
        12
    )

    pdf.cell(
        200,
        10,
        txt="AI Diagnosis",
        ln=True
    )

    pdf.set_font(
        "Arial",
        size=11
    )

    analysis = safe_text(
        analysis
    )

    pdf.multi_cell(
        0,
        8,
        analysis
    )

    # ==========================
    # PACKET STATISTICS
    # ==========================

    if stats:

        pdf.ln(5)

        pdf.set_font(
            "Arial",
            "B",
            12
        )

        pdf.cell(
            200,
            10,
            txt="Packet Statistics",
            ln=True
        )

        pdf.set_font(
            "Arial",
            size=11
        )

        pdf.cell(
            200,
            8,
            txt=f"TCP Packets: {stats['TCP']}",
            ln=True
        )

        pdf.cell(
            200,
            8,
            txt=f"UDP Packets: {stats['UDP']}",
            ln=True
        )

        pdf.cell(
            200,
            8,
            txt=f"DNS Packets: {stats['DNS']}",
            ln=True
        )

        pdf.cell(
            200,
            8,
            txt=f"DHCP Packets: {stats['DHCP']}",
            ln=True
        )

    # ==========================
    # AI INSIGHTS
    # ==========================

    if insights:

        pdf.ln(5)

        pdf.set_font(
            "Arial",
            "B",
            12
        )

        pdf.cell(
            200,
            10,
            txt="AI Network Insights",
            ln=True
        )

        pdf.set_font(
            "Arial",
            size=11
        )

        insights = safe_text(
            insights
        )

        pdf.multi_cell(
            0,
            8,
            insights
        )

    pdf.ln(10)

    pdf.set_font(
        "Arial",
        "I",
        10
    )

    pdf.cell(
        200,
        10,
        txt="Generated by AI Wireless Diagnostics Assistant",
        ln=True
    )

    filename = "wireless_report.pdf"

    pdf.output(
        filename
    )

    return filename